DROP TABLE USUARIO

CREATE TABLE USUARIO(
	IDUSUARIO SERIAL PRIMARY KEY,
	USUARIO VARCHAR(80) NOT NULL,
	SENHA VARCHAR(80) NOT NULL,
	DATACADASTRO VARCHAR(80) NOT NULL
)

SELECT * FROM USUARIO

DELETE FROM USUARIO